import {
    Trophy,
    Medal,
    Star,
    Zap,
    Calendar,
    Flame,
    Repeat,
    Target,
    Crown,
    Scroll,
    FlaskConical,
    Book,
    Gift,
    Sparkles,
    Timer,
    Diamond,
    Search,
    Lightbulb,
    Hourglass,
    CalendarDays,
    BarChart,
    Sword,
    Puzzle,
    Award,
    Bookmark,
    CheckCircle,
    Bug,
    CircuitBoard,
    Code,
    Code2,
    Cpu,
    Database,
    Terminal,
    Palette,
    Sun,
    Sigma,
    PartyPopper,
    FunctionSquare,
    Brain,
    Atom,
    Droplet,
    Leaf,
    Library,
    Grid,
    ChartBar,
    Scale,
    Infinity,
    Biohazard,
    Magnet,
} from 'lucide-react';

const badgesData = [
    {
        category: 'Milestone Badges',
        description: 'Celebrate reaching significant learning milestones.',
        badges: [
            {
                color: 'indigo',
                icon: PartyPopper,
                title: 'First Step',
                requirement: 'Complete your first quiz',
            },
            {
                color: 'indigo',
                icon: CheckCircle,
                title: 'Milestone Maker',
                requirement: 'Reach 10 completed quizzes',
            },
            {
                color: 'indigo',
                icon: Bookmark,
                title: 'Quiz Enthusiast',
                requirement: 'Reach 25 completed quizzes',
            },
            {
                color: 'indigo',
                icon: Medal,
                title: 'Quiz Achiever',
                requirement: 'Reach 50 completed quizzes',
            },
            {
                color: 'indigo',
                icon: Trophy,
                title: 'Quiz Champion',
                requirement: 'Reach 75 completed quizzes',
            },
            {
                color: 'indigo',
                icon: Crown,
                title: 'Century Club',
                requirement: 'Complete 100 quizzes',
            },
            {
                color: 'indigo',
                icon: Award,
                title: 'Elite Quizzer',
                requirement: 'Reach 300 completed quizzes',
            },
            {
                color: 'indigo',
                icon: Diamond,
                title: 'Quiz Legend',
                requirement: 'Reach 500 quizzes completed',
            },
        ],
    },
    {
        category: 'Achievement Badges',
        description: 'Recognizing outstanding quiz performance and consistency.',
        badges: [
            {
                color: 'blue',
                icon: Star,
                title: 'Quiz Master',
                requirement: 'Achieve 100% on a quiz',
            },
            {
                color: 'blue',
                icon: Hourglass,
                title: 'Doged The Clock',
                requirement: 'Achieve 90% or higher on a timed quiz',
            },
            {
                color: 'blue',
                icon: Lightbulb,
                title: 'Out-of-the-Box Thinker',
                requirement: 'Achieve 80% or higher on an expert level quiz',
            },
            {
                color: 'blue',
                icon: Puzzle,
                title: 'Puzzle Pro',
                requirement: 'Complete logic and brain-teaser quizzes with top scores.',
            },
            {
                color: 'blue',
                icon: Target,
                title: 'Precision Pro',
                requirement: 'Maintain a 90% or higher accuracy rate for 10 consecutive quizzes',
            },
            {
                color: 'blue',
                icon: Zap,
                title: 'Lightning Quick',
                requirement: 'Complete a quiz under a set time limit with high accuracy',
            },
            {
                color: 'blue',
                icon: Target,
                title: 'First Attempt Winner',
                requirement: 'Get a perfect score on the first attempt at a new quiz',
            },
            {
                color: 'blue',
                icon: Search,
                title: 'Hidden Gem',
                requirement: 'Find and complete a hidden or “easter egg” quiz',
            },
        ],
    },
    {
        category: 'Special Event Badges',
        description: 'Earn exclusive badges during special events and challenges.',
        badges: [
            {
                color: 'pink',
                icon: Gift,
                title: 'Challenge Champion',
                requirement: 'Win a weekly or monthly challenge',
            },
            {
                color: 'pink',
                icon: Sparkles,
                title: 'Event Participant',
                requirement: 'Join a special event or competition',
            },
            {
                color: 'pink',
                icon: Sword,
                title: 'Bold Challenger',
                requirement: 'Compete in a high-stakes quiz competition.',
            },
            {
                color: 'pink',
                icon: Calendar,
                title: 'Seasonal Superstar',
                requirement: 'Participate in a seasonal or holiday-themed quiz event',
            },
            {
                color: 'pink',
                icon: Timer,
                title: 'Trivia Titan',
                requirement: 'Join and complete a timed quiz competition',
            },
            {
                color: 'pink',
                icon: Flame,
                title: 'Victory Streak',
                requirement: 'Maintain a winning streak in challenge mode.',
            },
        ],
    },
    {
        category: 'Engagement Badges',
        description: 'Recognize consistent engagement and daily activity.',
        badges: [
            {
                color: 'teal',
                icon: Sun,
                title: 'Daily Streak',
                requirement: 'Log in and complete a quiz for 7 days straight',
            },
            {
                color: 'teal',
                icon: Flame,
                title: 'Weekly Warrior',
                requirement: 'Participate in a quiz every day for a week',
            },
            {
                color: 'teal',
                icon: CalendarDays,
                title: 'Monthly Marathoner',
                requirement: 'Engage in quizzes every day for a full month',
            },
            {
                color: 'teal',
                icon: Repeat,
                title: 'Persistent Learner',
                requirement: 'Return to review a quiz three times or more',
            },
        ],
    },
    {
        category: 'Humanities Badges',
        description: 'Celebrate your achievements in the arts, history, and literature.',
        badges: [
            {
                color: 'purple',
                icon: Scroll,
                title: 'History Buff',
                requirement: 'Complete 10 history quizzes with an average score of 85% or higher',
            },
            {
                color: 'purple',
                icon: Book,
                title: 'Literature Lover',
                requirement: 'Finish 10 literature quizzes and maintain an average score of 90%',
            },
            {
                color: 'purple',
                icon: Library,
                title: 'Philosophy Thinker',
                requirement: 'Score 80% or above on 4 philosophy quizzes',
            },
            {
                color: 'purple',
                icon: Palette,
                title: 'Renaissance Master',
                requirement: 'Finish 5 Renaissance art and history quizzes with an average of 85% or higher',
            },
        ],
    },
    {
        category: 'Math Badges',
        description: 'Prove your mathematical prowess and problem-solving abilities.',
        badges: [
            {
                color: 'orange',
                icon: Grid,
                title: 'Geometry Guru',
                requirement: 'Score 90% or higher in 5 geometry quizzes',
            },
            {
                color: 'orange',
                icon: Sigma,
                title: 'Math Whiz',
                requirement: 'Score 90% or higher on 10 math quizzes',
            },
            {
                color: 'orange',
                icon: Puzzle,
                title: 'Math Puzzle Master',
                requirement: 'Solve 10 math puzzles with scores above 80%',
            },
            {
                color: 'orange',
                icon: ChartBar,
                title: 'Statistics Specialist',
                requirement: 'Achieve a 90% average on 4 statistics quizzes',
            },
            {
                color: 'orange',
                icon: Scale,
                title: 'Algebra Ace',
                requirement: 'Complete 5 algebra quizzes with an average score of 85% or higher',
            },
            {
                color: 'orange',
                icon: Infinity,
                title: 'Calculus Crusader',
                requirement: 'Score 85% or higher on 3 advanced calculus quizzes',
            },
            {
                color: 'orange',
                icon: FunctionSquare,
                title: 'Function Master',
                requirement: 'Score 90% or higher in 5 calculus or trigonometry quizzes',
            },
            {
                color: 'orange',
                icon: Brain,
                title: 'Logic Genius',
                requirement: 'Achieve perfect scores in 5 logic or critical thinking quizzes',
            },
        ],
    },
    {
        category: 'Programming Badges',
        description: 'Show your skills and achievements in programming and computer science topics.',
        badges: [
            {
                color: 'sky',
                icon: Code,
                title: 'Programming Prodigy',
                requirement: 'Score 90% or higher on 5 programming language quizzes',
            },
            {
                color: 'sky',
                icon: BarChart,
                title: 'Data Diver',
                requirement: 'Score 75% or above in data interpretation quizzes',
            },
            {
                color: 'sky',
                icon: Terminal,
                title: 'Command Line Commander',
                requirement: 'Complete 10 quizzes on shell scripting and command-line operations',
            },
            {
                color: 'sky',
                icon: CircuitBoard,
                title: 'Algorithm Ace',
                requirement: 'Achieve 80% or higher on 7 algorithm-based quizzes',
            },
            {
                color: 'sky',
                icon: Cpu,
                title: 'Computer Science Enthusiast',
                requirement: 'Finish 5 advanced computer science quizzes with perfect scores',
            },
            {
                color: 'sky',
                icon: Bug,
                title: 'Debugging Dynamo',
                requirement: 'Successfully complete 5 debugging and error-finding quizzes with scores above 85%',
            },
            {
                color: 'sky',
                icon: Code2,
                title: 'Language Master',
                requirement: 'Score 90% or higher in quizzes on at least 3 different programming languages',
            },
            {
                color: 'sky',
                icon: Database,
                title: 'Database Guru',
                requirement: 'Complete 5 SQL or database management quizzes with scores above 85%',
            },
        ],
    },
    {
        category: 'Science Badges',
        description: 'Demonstrate your knowledge and expertise in various scientific fields.',
        badges: [
            {
                color: 'fuchsia',
                icon: FlaskConical,
                title: 'Science Scholar',
                requirement: 'Master 5 advanced science quizzes with perfect scores',
            },
            {
                color: 'fuchsia',
                icon: Sun,
                title: 'Solar Savant',
                requirement: 'Achieve 90% or higher in 3 solar system quizzes',
            },
            {
                color: 'fuchsia',
                icon: Atom,
                title: 'Physics Phenom',
                requirement: 'Score 85% or higher on 7 physics quizzes',
            },
            {
                color: 'fuchsia',
                icon: Biohazard,
                title: 'Eco Defender',
                requirement: 'Score 80% or higher in 5 environmental science quizzes',
            },
            {
                color: 'fuchsia',
                icon: Magnet,
                title: 'Electromagnet Expert',
                requirement: 'Complete 4 electromagnetism quizzes with scores above 85%',
            },
            {
                color: 'fuchsia',
                icon: Leaf,
                title: 'Biology Brainiac',
                requirement: 'Complete 10 biology quizzes with an average score of 80% or higher',
            },
            {
                color: 'fuchsia',
                icon: Droplet,
                title: 'Chemistry Champion',
                requirement: 'Finish 5 chemistry quizzes and score above 90%',
            },
        ],
    }
];

export default badgesData;
